apiVersion: apps/v1
kind: Deployment
metadata:
  name: loderunner
  namespace: ngsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loderunner
  template:
    metadata:
      labels:
        app: loderunner
        version: beta-0328-0252
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-lr:beta
          imagePullPolicy: Always

          args: 
          - -l
          - "1000"
          - -r
          - -s
          - http://ngsa-memory:8080
          - -f
          - benchmark.json
          - --prometheus
          - --zone
          - do-central
          - --region
          - Central

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner
  namespace: ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: loderunner

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner-np
  namespace: ngsa
  labels:
    app: loderunner

spec:
  type: NodePort
  selector:
    app: loderunner
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
