apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-memory
  namespace: ngsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngsa-memory
  template:
    metadata:
      labels:
        app: ngsa-memory
        version: beta-0328-2057
        deploy: 21-03-28-20-57-55
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-app:beta
          imagePullPolicy: Always

          args: 
          - --in-memory
          - --prometheus
          - --zone
          - az-central
          - --region
          - Central

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  namespace: ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ngsa-memory

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory-np
  namespace: ngsa
  labels:
    app: ngsa-memory

spec:
  type: NodePort
  selector:
    app: ngsa-memory
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
