# Default values for ngsa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  image:
    repository: ghcr.io/retaildevcrews/ngsa-app
    tag: beta-0.3.0-0321-0605-24
    pullPolicy: Always
  args: []
  port: 8080

service:
  type: ClusterIP
  port: 8080
